name 'nginx'
maintainer 'George Politis'
maintainer_email 'geo.politis@gmail.com'
license 'all_rights'
description 'Installs/Configures nginx'
long_description 'Installs/Configures nginx'
version '0.1.0'
